/*
Write and implements an application that simulate a simple slot machine 
in which three numbers between 0 and 9 are randomly
selected and printed side by side.
Print an appropriate statement if all three of the numbers are the same,
or if any two of the numbers are the same.
*/

package Random;

import java.util.*;

/**
 * This class simulates a slot machine game and checks for specific conditions in the slot machine numbers.
 */
public class PP58 {

    /**
     * The main method to run the simulation of the slot machine game.
     * @param args Command line arguments (not used).
     */
    public static void main(String[] args) {
        ArrayList<Integer> slotMachineNumbers = new ArrayList<Integer>();

        for (int i = 0; i < 1000; i++) {  
            slotMachineNumbers = slotMachine();
            if ((slotMachineNumbers.get(0) == slotMachineNumbers.get(1) &&
                slotMachineNumbers.get(1) == slotMachineNumbers.get(2)) && 
                slotMachineNumbers.get(0) + slotMachineNumbers.get(1) +
                slotMachineNumbers.get(2) == 300)
                System.out.println("Slot machine numbers: " + slotMachineNumbers);
        }
    }

    /**
     * Generates 3 random numbers for the slot machine.
     * @return An ArrayList containing the random numbers.
     */
    public static ArrayList<Integer> slotMachine() {
        Random random = new Random();
        ArrayList<Integer> slotNumbers = new ArrayList<Integer>();

        // Generate 3 random numbers between 0 and 9 (inclusive)
        for (int i = 1; i < 4; i++) {
            int randomNumber = random.nextInt(101);
            slotNumbers.add(randomNumber);
        }
        return slotNumbers;
    }

    /**
     * Checks if the numbers in the slot machine are equal.
     * @param slotMachineNumbers The numbers generated by the slot machine.
     */
    public static void areNumbersEqual(ArrayList<Integer> slotMachineNumbers) {
        // Check if all numbers in the slot machine are the same
        if (slotMachineNumbers.get(0) == slotMachineNumbers.get(1) &&
            slotMachineNumbers.get(1) == slotMachineNumbers.get(2)) {
            System.out.println("All numbers are the same. \n");
    
        // Check if at least two numbers in the slot machine are the same
        } else if (slotMachineNumbers.get(0) == slotMachineNumbers.get(1) ||
            slotMachineNumbers.get(0) == slotMachineNumbers.get(2) || 
            slotMachineNumbers.get(1) == slotMachineNumbers.get(2)) {
            System.out.println("Only two numbers are the same. \n");

        } else {
            System.out.println("None of the numbers are the same. \n");
        }
    }
}
